theme = "poimandres" 

[editor]
bufferline = "never"
auto-pairs = true 

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "separator","spinner", "file-name"]
right = ["version-control", "diagnostics", "position", "file-type"]
separator = "▾"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

