# Go
[[language]]
name = "go"
scope = "scope.go"
file-types = [ "go" ]
roots = [ "go.mod" ]
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = [ "gopls" ]
formatter = { command = "gofmt", args = [""] }

[language-server.gopls]
command = "gopls"

# Rust
[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rs|rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
shebangs = ["rust-script", "cargo"]
auto-format = true
comment-tokens = ["//", "///", "//!"]
block-comment-tokens = [
    { start = "/*", end = "*/" },
      { start = "/**", end = "*/" },
        { start = "/*!", end = "*/" },
]
language-servers = [ "rust-analyzer" ]
indent = { tab-width = 4, unit = "    " }
persistent-diagnostic-sources = ["rustc", "clippy"]

[language-server.rust-analyzer]
command = "rust-analyzer"

