# Go
[[language]]
name = "go"
scope = "scope.go"
file-types = [ "go" ]
roots = [ "go.mod" ]
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = [ "gopls" ]
formatter = { command = "gofmt", args = [""] }

[language-server.gopls]
command = "gopls"

# Rust
[[language]]
name = "rust"
scope = "source.rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
language-servers = [ "rust-analyzer" ]
persistent-diagnostic-sources = ["rustc", "clippy"]
auto-format = true
indent = { tab-width = 4, unit = "    " }
comment-tokens = ["//", "///", "//!"]
block-comment-tokens = [
    { start = "/*", end = "*/" },
      { start = "/**", end = "*/" },
        { start = "/*!", end = "*/" },
]

[language-server.rust-analyzer]
command = "rust-analyzer"

# Zig
[[language]]
name = "zig"
file-types = ["zig"]
roots = ["build.zig", "build.zig.zon"]
scope = "source.zig"
language-servers = [ "zls" ]
auto-format = true
indent = { tab-width = 4, unit = "    " }
comment-tokens = ["//", "///", "//!"]

[language-server.zls]
command = "zls"

# Gleam
[[language]]
name = "gleam"
scope = "source.gleam"
file-types = ["gleam"]
roots = ["gleam.toml"]
language-servers = ["gleam_lsp"]
auto-format = true
indent = { tab-width = 2, unit = "  " }
comment-tokens = ["//", "///"]
block-comment-tokens = [{ start = "/*", end = "*/" }]

[language-server.gleam_lsp]
command = "gleam"
args = ["lsp"]

# Bash
[[language]]
name = "bash"
language-servers = ["bash-language-server"]

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

